version: "3"
services:
  web:
    image: "bangtech/speech-fe:latest"
    user: "root"
    working_dir: /home/node/app
    ports:
      - 8080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    command: "docker-entrypoint.sh npm run dev"
